### ISSUE TITLE
Making the pull-request CI workflow faster

### ISSUE THREAD

**Issue by mightyiam** [ngi-nix/ngipkgs#104]
From #55, I understand that cachix is much faster than magic nix cache (also from experience in this project).

Also from #55 I understand that there are some security concerns for which we have two workflows, pull-request with the slow magic-nix-cache and push with the fast cachix.

Is there any way we could mitigate the security concern so that we could have only fast workflows with cachix?

@lorenzleutgeb

**Comment by lorenzleutgeb** [comment]
Good idea. Even better if PRs by members would then be automatically approved.

**Comment by lorenzleutgeb** [comment]
Since #177, "internal" PRs are now just as fast as the workflow that previously ran on the "push" event, and they use Cachix. With #104 I am making the next step: Removing Magic Nix Cache in favor of two the Cachix caches `ngi` and `ngi-untrusted`. The latter is considered world-writable. Pull requests from forks will use it to cache, and the "push" event (after merge by a member) will the populate the `ngi` Cache.

**Comment by lorenzleutgeb** [comment]
I think we've made good progress here, all workflows now use Cachix as was initially requested. @mightyiam if you agree feel free to close the issue, otherwise point me at jobs that are still taking too long for your taste. Thanks!

**Comment by fricklerhandwerk** [comment]
I'll close it as completed, let's open new, more specific issues when needed.

**Comment by mightyiam** [comment]
Thank you!
