### ISSUE TITLE
Update request: libeufin 0.9.3-dev.33 → 0.10.1

### ISSUE THREAD

**Issue by wegank** [ngi-nix/ngipkgs#214]
Looks like libeufin is a bit outdated compared to the other components: https://taler.net/en/news/2024-06.html

**Comment by fricklerhandwerk** [comment]
@alejandrosame could you please provide @wegank with a few pointers how to update the Maven dependencies? You were the last one touching that code. Maybe we'll get a bit of orientation for where to find the relevant documentation out of this.

**Comment by alejandrosame** [comment]
Hi!

Hopefully, Gradle support has improved since last time I tried this. If that is not the case, the way to manually fix the dependencies with the current `package.nix` is: 

- Change `version` and `src` as usual. Then the dependencies are prefetched in the line `deps = callPackage ./deps {inherit gradle patches pname src version;};` (no need to change anything here).
- After that, potentially there will be issues for gradle to find the Maven dependencies. If that's the case, they'll have to be patched manually like it was done with `use-maven-deps.patch`.

**Comment by fricklerhandwerk** [comment]
For reference, here's https://github.com/raphiz/buildGradleApplication by @raphiz who I met yesterday at #ZurichZHF. We briefly discussed this particular instance, which probably can't be helped by throwing more code at it, and what @alejandrosame proposes seems to be the most pragmatic solution, however hacky, short of fixing upstream following the suggestions in `buildGradleApplication`.
