### ISSUE TITLE
Librecast

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#3]
The Librecast project contributes to decentralising the Internet by enabling multicast. It builds transitional protocols and software to extend the reach of multicast and enable easy deployment by software developers.

- [NLnet project](https://nlnet.nl/project/LibreCastLiveStudio/)
- [librecast.net](https://librecast.net/librecast.html)
- source code:
  - https://codeberg.org/librecast
  - https://codeberg.org/librecast/lcrq
  - https://codeberg.org/librecast/librecast
- More information: https://github.com/ngi-nix/ngi/issues/122

There exists a Debian and Guix package. Developers and packagers are on IRC with a Matrix bridge, and also available via email for questions and guidance.

**Comment by albertchae** [comment]
@ngi-nix/moss is claiming this

**Comment by albertchae** [comment]
We have packaged `lcrq`, `librecast` and `lcsync`, which were the 3 targets identified by @cleeyv in https://github.com/ngi-nix/ngi/issues/122#issuecomment-1591866588. We are reaching out to librecast maintainers on https://todo.sr.ht/~librecast to identify there are any other suitable packaging targets.

**Comment by albertchae** [comment]
We are communicating with librecast maintainers on https://todo.sr.ht/~librecast/librecast/89 as well as IRC

**Comment by albertchae** [comment]
We upstreamed `lcrq`, `librecast` and `lcsync` to `nixpkgs` in https://github.com/NixOS/nixpkgs/pull/248437

**Comment by albertchae** [comment]
`lcrq` has been updated and `librecast` 0.7 will be out of RC soon, so we will update in nixpkgs accordingly after https://github.com/ngi-nix/ngipkgs/pull/36#issuecomment-1682025241

cc: @onepict

**Comment by albertchae** [comment]
This was merged a few weeks ago, but we bumped `librecast` to 0.7 in https://github.com/NixOS/nixpkgs/pull/250862

**Comment by albertchae** [comment]
I am closing this issue because I think we accomplished the goals of the issue under the scope of Summer of Nix.

There are 3 packages (`lcrq`, `librecast`, `lcsync`) listed on https://librecast.net/code.html
<img width="839" alt="image" src="https://github.com/ngi-nix/ngipkgs/assets/217050/8257adfe-eb77-4c82-b590-bc7d1c652d84">

And these are the 3 we both packaged into this repo `ngipkgs` and upstreamed into `nixpkgs`.

Furthermore, the members of our mob also committed to maintaining the packages in `nixpkgs`, so we can deal with any future version bumps as part of that responsibility separate from this github issue.

**Comment by fricklerhandwerk** [comment]
Good job @ngi-nix/moss!

**Comment by fricklerhandwerk** [comment]
Non-blocking clean-up to reduce duplication: https://github.com/ngi-nix/ngipkgs/issues/76
