### ISSUE TITLE
Rosenpass

### ISSUE THREAD

**Issue by fricklerhandwerk** [ngi-nix/ngipkgs#6]
Rosenpass is a formally verified, post-quantum secure VPN that uses WireGuard to transport the actual data.

- [NLnet project](https://nlnet.nl/project/Rosenpass/)
- [rosenpass.eu](https://rosenpass.eu/)
- [source code](https://github.com/rosenpass/rosenpass)

There already exists a `flake.nix` in the source repo. We can provide a NixOS module that allows plugging Rosenpass into Wireguard, or help with a distributed test setup.

The authors would like to see:
- Mac Support (M2 Architectures)
- BSD Support (Multiple architectures)
- Improving the efficiency of our Nix-based GitHub actions

**Comment by wucke13** [comment]
Hi, I did the initial work on our Nix stuff, so figured I brief you a little:

- currently, [packaging rosenpass](https://github.com/NixOS/nixpkgs/pull/218422) for NixOS is blocked by weird combination of bugs until when the liboqs-rust crate is update (relevant issue: https://github.com/open-quantum-safe/liboqs-rust/issues/213 ). What of course could be done in the meantime would be adding a module to the flake in our rosenpass repo.
- we have builds on `x86_64-darwin`, but nothing on `aarch64-darwin`. I'd be interested to get that, most preferable on GitHub Actions provided runners (as self-hosted runners really where terrible in our experience).
- I'd be also very interested in a NixOS (smoke-) test for `rosenpass` + `wireguard`, which would be a very nice extension to a module :smile: 
- regarding Determinate Systems magic nix cache I'm quite skeptical, we tried that in another project a couple of weeks ago and immediately reverted it after only a day, because we would hit the API rate-limits so fast. Currently we are running a cachix setup for Rosenpass, which seems to be okay-ish.
- currently rosenpass comes with some unix specific tools, and we do only have one package. For the future I'd like to have two packages, `rosenpass-unwrapped` (just the stuff you get from compiling rust), and `rosenpass` (containing also some shell scripts and unix specific tools). Then we could also attempt to provide a nix cross-compilation based windows build (for `x86_64-windows`).
- I'm am self-taught in Nix and outside of my bubble very few people reviewed my Nix code. I'd be very interested in receiving feedback on my work!

I hope that provides for a good discussion starter!
Kind regards, wucke13

**Comment by koraa** [comment]
Hi there,

I am the project lead of Rosenpass. Just checking in here :wave: 
@wucke13 is our nix expert; I think he can best handle the communication about this process

**Comment by lorenzleutgeb** [comment]
Hey @wucke13! The [mob](https://www.remotemobprogramming.org/) @ngi-nix/algae has picked this issue. We're finishing up other work at the moment, but our next issue will be this one. We'd like to implement a service, with [NixOS tests](https://nixos.org/manual/nixos/stable/#sec-nixos-tests) involving at least two VMs that peer successfully.

@fricklerhandwerk please clarify: Since there's a `flake.nix` upstream, should we directly contribute to upstream (i.e. definition of module containing service, tests) in the upstream repo, or should we just consume the upstream flake and implement module and tests in ngipkgs? If so, there are the corner cases of providing `aarch64-darwin` and `x86_64-windows` builds, that would probably best be upstreamed even if module and tests are kept in ngipkgs. I personally think that for the Rosenpass project it would make most sense to directly contribute to their repo, but I am not sure whether there are any constraints by NGI.

**Comment by fricklerhandwerk** [comment]
@lorenzleutgeb no constraints from our side. Just make sure that the result is also accessible through this repo as a single point of contact. Otherwise, do whatever is the most likely to succeed.

**Comment by lorenzleutgeb** [comment]
Alright. I forked Rosenpass at https://github.com/ngi-nix/rosenpass which algae will use to prepare a pull request against upstream, followed by a pull request against ngipkgs.

**Comment by andres-nav** [comment]
Status update:
@wucke13 after taking a look a the flake at the rosenpass repo, we had problems using it. For that reason we decided to  package `rosenpass` in `ngi-pkgs` repo in the [mob/algae-rosenpass](https://github.com/ngi-nix/ngipkgs/blob/mob/algae-rosenpass/pkgs/rosenpass/default.nix) branch first. We are using `buildRustPackage` and due to some dependency issues with `oqs-sys` we are packaging version `v0.2.0-rc.1`.

**Comment by wucke13** [comment]
> after taking a look a the flake at the rosenpass repo, we had problems using it.

@andres-nav can you please alaborate what problems you encountered?

Also, maybe you can take over https://github.com/NixOS/nixpkgs/pull/218422 once we release `0.2.0`?

**Comment by kubaneko** [comment]
@wucke13 We were not able to pass the rosenpass package to our nixos test configuration. We do not see a problem with taking over the  PR in nixpkgs. We have already finished packaging rosenpass in ngipkgs.

**Comment by andres-nav** [comment]
@wucke13 we are struggling to get rosenpass to work without the use of the `rp` script. We have two nixosTest vms (client and server). Would you please give us the exact list of commands without using `rp` (just `rosenpass`) which will allow us to successfully connect the vms with rosenpass + wireguard?
Also, we were wondering how does rosenpass rotate the preshared key, is it using a timer or wireguard tells rosenpass to do so.
Thank you for your time.

**Comment by augustebaum** [comment]
The [PR to nixpkgs](https://github.com/NixOS/nixpkgs/pull/254813) is now the most up-to-date version of the package and module (and test). We are waiting another review but we'll make sure to have the most up-to-date version in Ngipkgs before the end of Summer of Nix.

**Comment by koraa** [comment]
> @wucke13 we are struggling to get rosenpass to work without the use of the `rp` script. We have two nixosTest vms (client and server). Would you please give us the exact list of commands without using `rp` (just `rosenpass`) which will allow us to successfully connect the vms with rosenpass + wireguard?

Have you tried the `rp explain` option to generate the list of commands using `rp`?

>  Also, we were wondering how does rosenpass rotate the preshared key, is it using a timer or wireguard tells rosenpass to do so. Thank you for your time.

It is using a timer at the moment. A better solution would be tracking the output of `wg show all` (or rather the equivalent sysctl) to be absolutely sure that each key is used once.

**Comment by lorenzleutgeb** [comment]
In reply to @koraa: We're not using `rp` anymore, and we figured out that Rosenpass just calls `wg set` periodically. Our test checks that `wg show all preshared-keys` does not print `none`.

**Comment by koraa** [comment]
> In reply to @koraa: We're not using `rp` anymore, and we figured out that Rosenpass just calls `wg set` periodically. Our test checks that `wg show all preshared-keys` does not print `none`. Check `modules/rosenpass.nix` and `tests/eosenpass/` if you like.

I meant to figure out how to set up a tunnel without `rp`. The explain option was specifically designed to allow people to build setups without using the `rp` tool.

You call it once, get a list of commands and by sticking those into a shell script you can create a setup that is independ of `rp`.

**Comment by lorenzleutgeb** [comment]
Rosenpass package in Nixpkgs was updated, and there's now a Rosenpass module in NixOS that will make it into the 23.11 release. For more information, see https://github.com/NixOS/nixpkgs/pull/254813.

**Comment by koraa** [comment]
> Rosenpass package in Nixpkgs was updated, and there's now a Rosenpass module in NixOS that will make it into the 23.11 release. For more information, see [NixOS/nixpkgs#254813](https://github.com/NixOS/nixpkgs/pull/254813).

That is fantastic news. Thank you!

**Comment by fricklerhandwerk** [comment]
The Nixpkgs PR is merged. Non-blocking clean-up to reduce duplication: https://github.com/ngi-nix/ngipkgs/issues/76
