### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by lorenzleutgeb** [ngi-nix/ngipkgs#74]
I'd like to suggest to add metadata to the packages:

```nix
mkDerivation {
  # ...
  meta = {
    # The usual, standard meta-attributes, like `url`, `description`, `license`, ...
    # See <https://nixos.org/manual/nixpkgs/stable/#chap-meta>.
    description = "...";

    # Proposed custom meta-attribute:
    ngi = {
      # `project` refers to a URL of the form "https://nlnet.nl/project/${project}/"
      # the purpose is to establish a link to an NGI 
      project = "Example";

      # `main` is `true` if this package is the "main" package of the
      # project.
      main = true;

      # `options` designates which options (and their child options)
      # can be used to configure the project.
      # It is a list of paths, each of which is a list.
      options = [
        ["services" "example"]
      ];
    };
  };
}
```

What this enables:

 * Indexing of NGIpkgs by project.
 * Linking of projects to packages and modules (or rather, their options).
 * A "per-project view" of NGIpkgs.

Alternative: Instead of encoding this information as meta-attributes of derivations, we could also have a "registry", e.g. files `projects/${project}.nix` or so which contains a reference to the packages that are associated with the project and modules/options in a similar way as above. This might give us more flexibility, but would require one more file to maintain per project.

I think that configurations should also be exposed, but they are not mentioned in the above proposal yet.

**Comment by fricklerhandwerk** [comment]
Discussed with @lorenzleutgeb

Some updates on these ideas:

- Have all package recipes (those functions that take derivations and return a derivation) in `pkgs/by-name`

  Otherwise one has to *think* about every recipe where it belongs, this is cognitive overhead that we want to avoid for contributors.
   
- Each project has its own directory in `/projects` that corresponds to the project key at https://nlnet.nl/project/

  ```nix
  # /projects/Flarum/default.nix
  {
    pkgs ? import ../., # Nixpkgs + NGIpkgs
    sources ? (import ../../.).sources, # attrset of file system paths, denotes external dependencies
  }:
  {
     packages = {
       inherit (pkgs) flarum;
     };
    nixos.modules = {
      service = ./modules/flarum.nix; # the module system checks equality via file paths
      # there may be other things that one may want to import separately to avoid eval overhead
    };
    nixos.tests = {}; # attrset of NixOS tests, e.g. to be consumed by CI
    nixos.examples = {}; # attrset of attrset: { path = <path to config>;  description = <string>; } (could be just files with doc comments in the future, with post processing using something like nixdoc)
    # space for extra stuff, such as project-level meta-data (e.g. source, tags), documentation
  ```
  
   The `sources` pattern is not great, but at least it encapsulates external dependencies and makes them overrideable in principle. The ideal end state would be to allow taking the project directory in isolation and have it work, but that's currently not possible with existing tooling in the Nix ecosystem. We'll go for an approximation and can still fix forward when there are better solutions. These "compositional" interfaces should not be public anyway, for now.

- NixOS tests are per project, and thus live in the project's directory
