### ISSUE TITLE
Libervia-backend

### ISSUE THREAD

**Issue by augustebaum** [ngi-nix/ngipkgs#87]
Source code: https://repos.goffi.org/libervia-backend/

Part of #4

**Comment by jfly** [comment]
@alejandrosame, `sh` works via magic, if you do something like `from sh import foo`, it'll expect to find a `foo` binary somewhere on your PATH. The way to interpret this error is that the tests expect there to be a `li` binary somewhere on your PATH, and there isn't. It looks like that `li` binary is provided by libervia-backend itself, see its [pyproject.toml here](https://repos.goffi.org/libervia-backend/file/646b328b3980/pyproject.toml#l82).

**Comment by goffi-contrib** [comment]
Hello,

those tests using `sh` are the end-to-end tests, they need to be launched with the `run_e2e.py`. It is documented at https://libervia.org/__b/doc/backend/contributing/testing.html . They use docker images and mount the source inside the containers, there is normally nothing to install for them. However due to big architectural changes recently, they are currently broken, I'll fix them soon (I mostly need to update the docker images in `/docker`, this will also fix the local demo image).

Beside that, the tests in `tests/unit` are unit tests and can be run directly with `pytest` as long as you have a dev env installed.

I've moved recently to [Hatch](https://hatch.pypa.io/latest/), and to run the dev env, you can use `hatch -e dev shell`. However, I realize the the pytest modules are currently missing in my `pyproject.toml`, I'll fix that soon too.

Sorry for the temporarily broken things, it's a huge project, and it's difficult to keep everything running immediately when I'm doing big structural changes.

**Comment by augustebaum** [comment]
Closed for now, see https://github.com/ngi-nix/ngipkgs/issues/4#issuecomment-1786916017
